name: haskell-lib-test-user

dependencies:
  - base >= 4.7 && < 5
  - haskell-lib-test-wrapper

executables:
  app:
    source-dirs:
      - app
    main: Main.hs
    extra-lib-dirs:
      - ./lib/v1
