resolver: lts-22.11
compiler: ghc-9.6.4

packages:
  - .

extra-deps:
  - git: https://github.com/kevorr/haskell-lib-test
    commit: 1c625ea3462fe957e23daefcf5bb98e410b7bff8
    subdirs:
      - haskell-wrapper

extra-lib-dirs:
  - /Users/kevin/work/bs/haskell-libs-test/lib/v2
